NORD_BACKGROUND = "#2e3440"
NORD_FOREGROUND = "#eceff4"
FROST_TEAL = "#a3be8c"
SLATE_GRAY = "#657b83"
FROST_AZURE = "#6ca1c1"
AURORA_GREEN = "#a3be8c"
AURORA_PURPLE = "#a78ea2"
FROST_AQUA = "#88b3b3"
AURORA_RED = "#bf616a"
AURORA_YELLOW = "#ebcb8b"
NORD_BLUE = "#5e81ac"

POIMANDRES_BACKGROUND = "#292e39"
POIMANDRES_FOREGROUND = "#eceff4"
NORD_COLORS = [
    FROST_TEAL,
    SLATE_GRAY,
    FROST_AZURE,
    AURORA_GREEN,
    AURORA_PURPLE,
    FROST_AQUA,
    AURORA_RED,
]
